# Generated by Django 4.1.7 on 2023-04-25 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("manageApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="entry_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="入职时间"
            ),
            preserve_default=False,
        ),
    ]
