# Generated by Django 4.1.7 on 2023-05-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageApp", "0002_prettynum_alter_department_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prettynum",
            name="price",
            field=models.FloatField(default=0.0, verbose_name="价格"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(verbose_name="年龄"),
        ),
    ]
