# Generated by Django 4.1.7 on 2023-05-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manageApp", "0003_alter_prettynum_price_alter_userinfo_age"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prettynum", old_name="leve", new_name="level",
        ),
    ]
