# Generated by Django 4.1.7 on 2023-06-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageApp", "0004_rename_leve_prettynum_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=128, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
    ]
