# Generated by Django 4.1.7 on 2023-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageApp", "0005_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="signup_time",
            field=models.DateTimeField(null=True, verbose_name="注册时间"),
        ),
    ]
