# Generated by Django 4.1.7 on 2023-07-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageApp", "0010_alter_admin_signup_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="update_time",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="最后修改时间"),
        ),
    ]
